#
# Makefile for Unisys SPAR drivers
#
obj-$(CONFIG_UNISYS_VISORUTIL)		+= visorutil/
obj-$(CONFIG_UNISYS_VISORCHANNEL)	+= visorchannel/
obj-$(CONFIG_UNISYS_VISORCHIPSET)	+= visorchipset/
obj-$(CONFIG_UNISYS_VISORBUS)		+= visorbus/
obj-$(CONFIG_UNISYS_VISORHID)		+= visorhid/
obj-$(CONFIG_UNISYS_UISLIB)		+= uislib/
obj-$(CONFIG_UNISYS_VIRTPCI)		+= virtpci/
obj-$(CONFIG_UNISYS_VIRTHBA)		+= virthba/
